# Generated by Django 6.0.1 on 2026-02-03 05:14

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosPersonales',
            fields=[
                ('idperfil', models.AutoField(primary_key=True, serialize=False)),
                ('descripcionperfil', models.CharField(max_length=50)),
                ('perfilactivo', models.IntegerField(default=1)),
                ('apellidos', models.CharField(max_length=60)),
                ('nombres', models.CharField(max_length=60)),
                ('nacionalidad', models.CharField(max_length=20)),
                ('lugarnacimiento', models.CharField(max_length=60)),
                ('fechanacimiento', models.DateField()),
                ('numerocedula', models.CharField(max_length=10, unique=True)),
                ('sexo', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=1)),
                ('estadocivil', models.CharField(max_length=50)),
                ('licenciaconducir', models.CharField(blank=True, max_length=6, null=True)),
                ('telefonoconvencional', models.CharField(blank=True, max_length=15, null=True)),
                ('telefonofijo', models.CharField(blank=True, max_length=15, null=True)),
                ('direcciontrabajo', models.CharField(blank=True, max_length=50, null=True)),
                ('direcciondomiciliaria', models.CharField(blank=True, max_length=50, null=True)),
                ('sitioweb', models.CharField(blank=True, max_length=60, null=True)),
                ('foto_perfil', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
            ],
            options={
                'verbose_name': 'Dato Personal',
                'verbose_name_plural': 'Datos Personales',
                'db_table': 'datospersonales',
            },
        ),
        migrations.CreateModel(
            name='CursosRealizados',
            fields=[
                ('idcursorealizado', models.AutoField(primary_key=True, serialize=False)),
                ('nombrecurso', models.CharField(max_length=100)),
                ('fechainicio', models.DateField()),
                ('fechafin', models.DateField()),
                ('totalhoras', models.IntegerField()),
                ('descripcioncurso', models.TextField(blank=True, null=True)),
                ('entidadpatrocinadora', models.CharField(max_length=100)),
                ('nombrecontactoauspicia', models.CharField(blank=True, max_length=100, null=True)),
                ('telefonocontactoauspicia', models.CharField(blank=True, max_length=60, null=True)),
                ('emailempresapatrocinadora', models.CharField(blank=True, max_length=60, null=True)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('rutacertificado', cloudinary.models.CloudinaryField(blank=True, help_text='Certificado en PDF', max_length=255, null=True, verbose_name='archivo')),
                ('idperfilconqueestaactivo', models.ForeignKey(db_column='idperfilconqueestaactivo', on_delete=django.db.models.deletion.CASCADE, to='curriculum.datospersonales')),
            ],
            options={
                'verbose_name': 'Curso Realizado',
                'verbose_name_plural': 'Cursos Realizados',
                'db_table': 'cursosrealizados',
                'ordering': ['-fechainicio'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionSecciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mostrar_perfil', models.BooleanField(default=True, verbose_name='Mostrar Perfil Profesional')),
                ('mostrar_experiencia', models.BooleanField(default=True, verbose_name='Mostrar Experiencia Laboral')),
                ('mostrar_reconocimientos', models.BooleanField(default=True, verbose_name='Mostrar Reconocimientos')),
                ('mostrar_cursos', models.BooleanField(default=True, verbose_name='Mostrar Cursos Realizados')),
                ('mostrar_productos_academicos', models.BooleanField(default=True, verbose_name='Mostrar Productos Académicos')),
                ('mostrar_productos_laborales', models.BooleanField(default=True, verbose_name='Mostrar Productos Laborales')),
                ('mostrar_venta_garage', models.BooleanField(default=True, verbose_name='Mostrar Venta Garage')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.datospersonales')),
            ],
            options={
                'verbose_name': 'Configuración de Secciones',
                'verbose_name_plural': 'Configuraciones de Secciones',
            },
        ),
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('idexperiencialaboral', models.AutoField(primary_key=True, serialize=False)),
                ('cargodesempenado', models.CharField(max_length=100)),
                ('nombreempresa', models.CharField(max_length=50)),
                ('lugarempresa', models.CharField(blank=True, max_length=50, null=True)),
                ('emailempresa', models.CharField(blank=True, max_length=100, null=True)),
                ('sitiowebempresa', models.CharField(blank=True, max_length=100, null=True)),
                ('nombrecontactoempresarial', models.CharField(blank=True, max_length=100, null=True)),
                ('telefonocontactoempresarial', models.CharField(blank=True, max_length=60, null=True)),
                ('fechainiciogestion', models.DateField()),
                ('fechafingestion', models.DateField(blank=True, null=True)),
                ('descripcionfunciones', models.TextField(blank=True, null=True)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('rutacertificado', models.FileField(blank=True, null=True, upload_to='certificados/experiencia/')),
                ('idperfilconqueestaactivo', models.ForeignKey(db_column='idperfilconqueestaactivo', on_delete=django.db.models.deletion.CASCADE, to='curriculum.datospersonales')),
            ],
            options={
                'verbose_name': 'Experiencia Laboral',
                'verbose_name_plural': 'Experiencias Laborales',
                'db_table': 'experiencialaboral',
                'ordering': ['-fechainiciogestion'],
            },
        ),
        migrations.CreateModel(
            name='ProductosAcademicos',
            fields=[
                ('idproductoacademico', models.AutoField(primary_key=True, serialize=False)),
                ('nombrerecurso', models.CharField(max_length=100)),
                ('clasificador', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('idperfilconqueestaactivo', models.ForeignKey(db_column='idperfilconqueestaactivo', on_delete=django.db.models.deletion.CASCADE, to='curriculum.datospersonales')),
            ],
            options={
                'verbose_name': 'Producto Académico',
                'verbose_name_plural': 'Productos Académicos',
                'db_table': 'productosacademicos',
            },
        ),
        migrations.CreateModel(
            name='ProductosLaborales',
            fields=[
                ('idproductolaboral', models.AutoField(primary_key=True, serialize=False)),
                ('nombreproducto', models.CharField(max_length=100)),
                ('fechaproducto', models.DateField()),
                ('descripcion', models.TextField()),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('idperfilconqueestaactivo', models.ForeignKey(db_column='idperfilconqueestaactivo', on_delete=django.db.models.deletion.CASCADE, to='curriculum.datospersonales')),
            ],
            options={
                'verbose_name': 'Producto Laboral',
                'verbose_name_plural': 'Productos Laborales',
                'db_table': 'productoslaborales',
                'ordering': ['-fechaproducto'],
            },
        ),
        migrations.CreateModel(
            name='Reconocimientos',
            fields=[
                ('idreconocimiento', models.AutoField(primary_key=True, serialize=False)),
                ('tiporeconocimiento', models.CharField(choices=[('Académico', 'Académico'), ('Público', 'Público'), ('Privado', 'Privado')], max_length=100)),
                ('fechareconocimiento', models.DateField()),
                ('descripcionreconocimiento', models.TextField()),
                ('entidadpatrocinadora', models.CharField(max_length=100)),
                ('nombrecontactoauspicia', models.CharField(blank=True, max_length=100, null=True)),
                ('telefonocontactoauspicia', models.CharField(blank=True, max_length=60, null=True)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('rutacertificado', cloudinary.models.CloudinaryField(blank=True, help_text='Certificado en PDF', max_length=255, null=True, verbose_name='archivo')),
                ('idperfilconqueestaactivo', models.ForeignKey(db_column='idperfilconqueestaactivo', on_delete=django.db.models.deletion.CASCADE, to='curriculum.datospersonales')),
            ],
            options={
                'verbose_name': 'Reconocimiento',
                'verbose_name_plural': 'Reconocimientos',
                'db_table': 'reconocimientos',
                'ordering': ['-fechareconocimiento'],
            },
        ),
        migrations.CreateModel(
            name='VentaGarage',
            fields=[
                ('idventagarage', models.AutoField(primary_key=True, serialize=False)),
                ('nombreproducto', models.CharField(max_length=100)),
                ('estadoproducto', models.CharField(choices=[('Bueno', 'Bueno'), ('Regular', 'Regular')], max_length=40)),
                ('descripcion', models.TextField()),
                ('valordelbien', models.DecimalField(decimal_places=2, max_digits=7)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('imagen_producto', cloudinary.models.CloudinaryField(blank=True, help_text='Imagen del producto en venta', max_length=255, null=True, verbose_name='image')),
                ('idperfilconqueestaactivo', models.ForeignKey(db_column='idperfilconqueestaactivo', on_delete=django.db.models.deletion.CASCADE, to='curriculum.datospersonales')),
            ],
            options={
                'verbose_name': 'Venta Garage',
                'verbose_name_plural': 'Ventas Garage',
                'db_table': 'ventagarage',
            },
        ),
    ]
